[workspace]
resolver = "2"
members = [
    "serde-query",
    "serde-query-core",
    "serde-query-derive",
]

[workspace.dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.51"
quote = "1.0.23"
serde = "1"
serde_json = "1"
syn = "2.0.106"